# ansible-playbook.yaml
- name: Init packages
  hosts: all
  # vars_files:
  #   - ./vars/variables.yml
  tasks:
    - name: Update repositories cache and install dependencies
      become: yes
      ansible.builtin.apt:
        pkg:
          - software-properties-common
          - gnupg
        update_cache: yes

    - name: Download gpg
      become: yes
      ansible.builtin.shell: |
        wget -O /tmp/file-gpg https://apt.releases.hashicorp.com/gpg
        gpg --dearmor /tmp/file-gpg 
        mv /tmp/file-gpg.gpg /usr/share/keyrings/hashicorp-archive-keyring.gpg 

    - name: Actualizar el índice del repositorio APT
      ansible.builtin.apt:
        update_cache: yes

    - name: Generar contenido del archivo de lista de fuentes
      become: yes
      ansible.builtin.template:
        src: hashicorp.list.j2
        dest: /etc/apt/sources.list.d/hashicorp.list

    - name: Actualizar el índice del repositorio
      ansible.builtin.apt:
        update_cache: yes

    - name: Update repositories cache and terraform 
      become: yes
      ansible.builtin.apt:
        name: terraform=1.1.5
        update_cache: yes

    - name: Copiar archivos desde el nodo de control al nodo remoto
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: ~/terraform_challenge/{{ item | basename }}
      with_fileglob:
        - "terraform/*"


